-- MySQL Script generated by MySQL Workbench
-- pią, 8 kwi 2022, 18:26:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HMSDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HMSDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HMSDB` ;
USE `HMSDB` ;

-- -----------------------------------------------------
-- Table `HMSDB`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HMSDB`.`user` ;

CREATE TABLE IF NOT EXISTS `HMSDB`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `is_employee` TINYINT(1) NOT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HMSDB`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HMSDB`.`patient` ;

CREATE TABLE IF NOT EXISTS `HMSDB`.`patient` (
  `idpatient` INT NOT NULL AUTO_INCREMENT,
  `user` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `date_of_birth` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  PRIMARY KEY (`idpatient`),
  INDEX `fk_patient_user1_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `fk_patient_user1`
    FOREIGN KEY (`user`)
    REFERENCES `HMSDB`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HMSDB`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HMSDB`.`department` ;

CREATE TABLE IF NOT EXISTS `HMSDB`.`department` (
  `iddepartment` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`iddepartment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HMSDB`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HMSDB`.`role` ;

CREATE TABLE IF NOT EXISTS `HMSDB`.`role` (
  `idrole` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idrole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HMSDB`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HMSDB`.`employee` ;

CREATE TABLE IF NOT EXISTS `HMSDB`.`employee` (
  `idemployee` INT NOT NULL AUTO_INCREMENT,
  `user` INT NOT NULL,
  `department` INT NOT NULL,
  `role_idrole` INT NOT NULL,
  `employee_number` VARCHAR(8) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `date_of_birth` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  PRIMARY KEY (`idemployee`),
  INDEX `fk_employee_department1_idx` (`department` ASC) VISIBLE,
  INDEX `fk_employee_user1_idx` (`user` ASC) VISIBLE,
  INDEX `fk_employee_role1_idx` (`role_idrole` ASC) VISIBLE,
  CONSTRAINT `fk_employee_department1`
    FOREIGN KEY (`department`)
    REFERENCES `HMSDB`.`department` (`iddepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_user1`
    FOREIGN KEY (`user`)
    REFERENCES `HMSDB`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_role1`
    FOREIGN KEY (`role_idrole`)
    REFERENCES `HMSDB`.`role` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HMSDB`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HMSDB`.`room` ;

CREATE TABLE IF NOT EXISTS `HMSDB`.`room` (
  `idroom` INT NOT NULL AUTO_INCREMENT,
  `department` INT NOT NULL,
  `number` VARCHAR(8) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`idroom`),
  INDEX `fk_room_department1_idx` (`department` ASC) VISIBLE,
  CONSTRAINT `fk_room_department1`
    FOREIGN KEY (`department`)
    REFERENCES `HMSDB`.`department` (`iddepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HMSDB`.`appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HMSDB`.`appointment` ;

CREATE TABLE IF NOT EXISTS `HMSDB`.`appointment` (
  `idappointment` INT NOT NULL AUTO_INCREMENT,
  `patient` INT NOT NULL,
  `employee` INT NOT NULL,
  `room` INT NOT NULL,
  `date` DATE NULL,
  `time` TIME NULL,
  PRIMARY KEY (`idappointment`),
  INDEX `fk_appointment_room1_idx` (`room` ASC) VISIBLE,
  INDEX `fk_appointment_patient1_idx` (`patient` ASC) VISIBLE,
  INDEX `fk_appointment_employee1_idx` (`employee` ASC) VISIBLE,
  CONSTRAINT `fk_appointment_room1`
    FOREIGN KEY (`room`)
    REFERENCES `HMSDB`.`room` (`idroom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_patient1`
    FOREIGN KEY (`patient`)
    REFERENCES `HMSDB`.`patient` (`idpatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_employee1`
    FOREIGN KEY (`employee`)
    REFERENCES `HMSDB`.`employee` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HMSDB`.`stay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HMSDB`.`stay` ;

CREATE TABLE IF NOT EXISTS `HMSDB`.`stay` (
  `idstay` INT NOT NULL AUTO_INCREMENT,
  `room` INT NOT NULL,
  `patient` INT NOT NULL,
  `start_date` DATE NULL,
  `end_date` VARCHAR(45) NULL,
  PRIMARY KEY (`idstay`),
  INDEX `fk_stay_room1_idx` (`room` ASC) VISIBLE,
  INDEX `fk_stay_patient1_idx` (`patient` ASC) VISIBLE,
  CONSTRAINT `fk_stay_room1`
    FOREIGN KEY (`room`)
    REFERENCES `HMSDB`.`room` (`idroom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stay_patient1`
    FOREIGN KEY (`patient`)
    REFERENCES `HMSDB`.`patient` (`idpatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HMSDB`.`prescription_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HMSDB`.`prescription_history` ;

CREATE TABLE IF NOT EXISTS `HMSDB`.`prescription_history` (
  `idprescription` INT NOT NULL AUTO_INCREMENT,
  `appointment` INT NULL,
  `stay` INT NULL,
  `result` VARCHAR(45) NULL,
  PRIMARY KEY (`idprescription`),
  INDEX `fk_prescription_history_appointment1_idx` (`appointment` ASC) VISIBLE,
  INDEX `fk_prescription_history_stay1_idx` (`stay` ASC) VISIBLE,
  CONSTRAINT `fk_prescription_history_appointment1`
    FOREIGN KEY (`appointment`)
    REFERENCES `HMSDB`.`appointment` (`idappointment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prescription_history_stay1`
    FOREIGN KEY (`stay`)
    REFERENCES `HMSDB`.`stay` (`idstay`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `user` (`is_employee`,`email`,`password`)
VALUES
  (0,"urna.suscipit.nonummy@protonmail.net",5359),
  (0,"lectus@google.com",5548),
  (1,"eu.sem.pellentesque@aol.couk",5139),
  (2,"mattis.integer.eu@hotmail.ca",5008),
  (1,"aliquam.iaculis@outlook.ca",5131);
